FROM python:3.6

# simplified
#
# pip install tensorboard
#
# doesn't work because tensorboard requires tensorflow
# so we should install both

RUN pip install --upgrade pip \
 && pip install --default-timeout=1000 --no-cache-dir tensorflow

CMD tensorboard --logdir $LOGS_PATH
